### ISSUE TITLE
Surname should be before name and mandatory field in case of pseudonyms and such

### ISSUE THREAD

**Issue by ubriquejazz** [imoren2x/django_polska_biblioteka#6]

**Comment by imoren2x** [comment]
This request should have been two, indeed, 
* one for the name order,
* and the other for the pseudonyms.

Surname is already written before the name in the current version.

About author's pseudonyms, it is just necessary to write the name of the author as a pseudonym.

I post the following image as test evidence:

![image](https://user-images.githubusercontent.com/35999100/97802211-1cb56000-1c42-11eb-9cee-4ddd6c4c653c.png)

I hereby consider this issue as closed, otherwise, just re-open it and I will carry it out.
